name: qiniu_upload_plugin
version: 0.0.1
language:
description: qiniu upload plugin, used to save a file to qiniu cdn.
tags:
 - qiniu
 - qiniu_upload
 - plugin

public: false

# clone_in_docker: false

inputs:
  - name: FLOW_QINIU_ACCESS_KEY
    desc_cn: "7牛提供的access_key"
    editable: true

  - name: FLOW_QINIU_SECRET_KEY
    desc_cn: "7牛提供的 secret_key"
    editable: true

  - name: FLOW_QINIU_BUCKET
    desc_cn: "7牛提供的 secret_bucket"
    editable: true

  - name: FLOW_QINIU_KEY
    desc_cn: "7牛提供的KEY"
    editable: true

  - name: FLOW_QINIU_LOCAL_FILE
    desc_cn: "在机器上需要上传的文件"
    editable: true

outputs:
  - name: FLOW_QINIU_RESULT

script_path: ./run.sh
